- hosts: all
  name: Playing with ansible
  become: true
  become_user: root
  tasks:
    - name: Update packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400

    - name: Install openssh-server
      apt:
        name: openssh-server

    - name: Create user called test
      ansible.builtin.user:
        name: test
        uid: 1012
        group: sudo
        createhome: yes
        home: /home/test

    - name: Add SSH Keys
      ansible.posix.authorized_key:
        user: test
        state: present
        key: "{{ lookup('file', 'test-key.pub') }}"

    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Install fail2ban if absent
      apt:
        name: fail2ban
        state: present
      when: 
        - "'fail2ban' not in ansible_facts.packages"
